<div id="app">
   <?php display_notifications() ?>
   <div class="main-wrapper main-wrapper-1">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar"></nav>
      <!-- Main Content -->
      <div class="main-content">
         <section class="section">
            <div class="section-header">
               <div class="section-header-back">
                  <a href="features-settings.html" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
               </div>
               <h1>Changelogs & New things</h1>
            </div>
            <div class="section-body">
               <h2 class="section-title">All About Changelogs</h2>
               <p class="section-lead">
                  Here you can see the history of each update to Phoenix!
               </p>
            </div>
         </section>
		  <div class="card card-dark">
              <div class="card-header">
                 <h4>1.0.1</h4>
              </div>
              <div class="card-body">
                 <ul>
					 <li>Initial Release 🎉🔥</li>
				 </ul>
              </div>
           </div>
      </div>
   </div>
</div>