<div id="app">
   <?php display_notifications() ?>
   <div class="main-wrapper main-wrapper-1">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar"></nav>
      <!-- Main Content -->
      <div class="main-content">
         <section class="section">
            <div class="section-header">
               <div class="section-header-back">
                  <a href="features-settings.html" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
               </div>
               <h1>General Settings</h1>
            </div>
            <div class="section-body">
               <h2 class="section-title">All About General Settings</h2>
               <p class="section-lead">
                  Here you can manage the general information of your site, such as website title, description, and language.
               </p>
            </div>
         </section>
		   <table class="table table-striped table-dark">
                      <thead>
                        <tr>
                          <th scope="col" >Title</th>
                    		<th scope="col" >Link</th>
                    		<th scope="col">Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                   
                          <?php while($row = $data->pages_result->fetch_object()): ?>

            <tr>
                <td><?= $row->title ?></td>
                <td>
                    <a href="<?= (strpos($row->url, 'http://') !== false || strpos($row->url, 'https://') !== false) ? $row->url : url('page/' . $row->url) ?>" target="_blank">
                        <i class="fa fa-sm fa-link"></i> <?= $row->url ?>
                    </a>
                </td>
                <td><?= get_admin_options_button('page', $row->page_id) ?></td>
            

        <?php endwhile ?>  
                        </tr>
                      </tbody>
                    </table>
      </div>
   </div>
</div>