<style>
  h1 { font-size: 50px; }
  article { display: block; text-align: center; width: 650px; margin:140px;}
  a { color: #dc8100; text-decoration: none; }
  a:hover { color: #333; text-decoration: none; }
</style>
<div class = "container">
<article>
	<div class = "card" style = "width:800px;padding:15px;">
    <h1>404</h1>
    <div>
        <p>Hmm, We could not find that page. Perhaps our developer fell asleep again.</p>
    </div>
	</div>
</article>
</div>
