<div class = "container">
<div class = "row">
<div class = "col-md-9 offset-2 m-5">
<div class="card card-primary">
    <div class="card-header">
        <h2><?php echo $this->settings->title ?></h2>
    </div>
    <div class="card-body">
        <p>Phoenix CMS has been installed on <code><?php echo SITE_URL ?></code>! 🎉 </p>
        <br>
        <p>Visit our docs or join our Discord server to get excellent support on how to start using Phoenix CMS. You can also search YouTube for our wide varietry of tutorials covering several aspects of Phoenix CMS.</p>
    </div>
</div>
</div>
</div>
</div>