<div id="app">
   <?php display_notifications() ?>
   <div class="main-wrapper main-wrapper-1">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar"></nav>
      <!-- Main Content -->
      <div class="main-content">
         <section class="section">
            <div class="section-header">
               <div class="section-header-back">
                  <a href="features-settings.html" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
               </div>
               <h1><?php echo $this->settings->title ?> API</h1>
            </div>
            <div class="section-body">
               <h2 class="section-title">All about Personnal API</h2>
               <p class="section-lead">
                  Here you can manage your own website API to add users, make posts, and more!
               </p>
            </div>
         </section>
		 <div class="alert alert-primary alert-has-icon">
            <div class="alert-icon"><i class="far fa-lightbulb"></i></div>
                <div class="alert-body">
                    <div class="alert-title">Just a tip!</div>
                        When testing out your API's a helpful tool to use is <a class = "alert-link" href = "https://www.postman.com/" target = "_blank">Postman</a>.
                    </div>
                </div>
		 <div class="row">
            <div class="col-md-8">
              <div class="card">
                <div class="card-body">
                  <form action="" method="post" role="form" enctype="multipart/form-data">
                    <input type="hidden" name="token" value="<?= \Phoenix\Middlewares\Csrf::get() ?>" />
                    <div class="row">
					  <div class="col-md-12">
                        <div class="form-group">
                          <label class="bmd-label-floating"><?php echo $this->settings->title ?> API Key</label>
                          <input type="text" class="form-control" value = "<?= $this->settings->personal_key ?>" disabled>
                        </div>
						  <button type = "submit"  class ="btn btn-primary" name = "generate_api_key">Generate New Key</button>
						  <hr>
                      </div>				 
                      
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bmd-label-floating">Test Endpoint</label>
                           <select class="custom-select" name="test_api">
                                    <option value="1" <?= $this->settings->test_api ? 'selected' : null ?>>Enabled</option>
                                    <option value="0" <?= !$this->settings->test_api ? 'selected' : null ?>>Disabled</option>
                            </select>
							<small class="text-muted">Enable or disable this endpoint.</small>
                        </div>
                      </div>

                    </div>
                    <button type="submit" name = "save" class="btn btn-primary">Save</button>
                    <div class="clearfix"></div>
                  </form>
                </div>
              </div>
            </div>
  		    </div>
		 </div>
   </div>
</div>