<?php display_notifications() ?>
<div class = "container">
<div class = "row">
<div class = "col-md-10 offset-3 m-5">
<div class="card card-warning">
                  <div class="card-header">
                    <h4>Welcome back, <?php echo $this->user->username ?></h4>
                  </div>
                  <div class="card-body">
                    <p>This is the user dashboard. Use the <code>dashboard</code> hook to add data into the user dashboard.</p>
                  </div>
                </div>
</div>
</div>
</div>