<?php display_notifications() ?>
<div class = "container">
    <div class = "card" style = "margin:80px">
        <div class = "card-body">
			<div class = "card-title"><h1><?php echo $this->settings->title ?> | <?php lang('dashboard') ?></h1></div>
           Welcome to the user dashboard! This is where you can add content related to each user. (payment details, account details, etc). You can add content through the dashboard view at core/themes/YOUR_THEME/layout/dashboard.
        </div>
    </div>
<div>