<div class = "container">
	<div class = "row">
		<div class = "col-md-9 offset-2">
			<div class = "card card-info m-4">
				<div class = "card-header">
					<div class = "card-title">Coming Soon 🤔</div>
				</div>
				<div class = "card-body">
					<div class = "card-text">In upcoming updates you will have access to your very own website API for data handling. 💾</div>
				</div>
			</div>
		</div>
	</div>
</div>