<div id="app">
   <?php display_notifications() ?>
   <div class="main-wrapper main-wrapper-1">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar"></nav>
      <!-- Main Content -->
      <div class="main-content">
         <section class="section">
            <div class="section-header">
               <div class="section-header-back">
                  <a href="features-settings.html" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
               </div>
               <h1>User Management</h1>
            </div>
            <div class="section-body">
               <h2 class="section-title">All About User Management</h2>
               <p class="section-lead">
                  Here you can manage the users and their details.
               </p>
            </div>
         </section>
		   <table class="table table-striped table-dark">
                      <thead>
                        <tr>
                          <th scope="col" >User ID</th>
                    		<th scope="col" >Username</th>
                    		<th scope="col" >Email</th>
                    		<th scope="col">IP</th>
                    		<th scope="col" >Status</th>
                    		<th scope="col">Permissions</th>
                    		<th scope="col">Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php
                       $users_sql = "SELECT * FROM users";
	                   $users_result = Phoenix\Database\Database::$database->query($users_sql);
	                    while($row = $users_result->fetch_assoc()){ ?>
	                    <?php
	                    switch($row['type']){
	                        case '1':
	                            $type = "Admin";
	                        break;
	                        case '0';
	                            $type = "User";
	                       break;
	                    }
	                    
	                       switch($row['active']){
	                        case '1':
	                            $active = "
	                            
	                            <div class='badges'>
                      			<span class='badge badge-success'>Active</span>
	                            </div>
								
	                            ";
	                        break;
	                        case '0';
	                            $active = "
	                            
	                            <div class='badges'>
                      			<span class='badge badge-warning'>Disabled</span>
	                            </div>
	                            
	                            ";
	                       break;
	                        }
	                    ?>
	                    <tr>
                        <td><?php echo $row['user_id'] ?></td>
                        <td><?php echo $row['username'] ?></td>
                        <td><?php echo $row['email'] ?></td>
                        <td><?php echo $row['ip'] ?></td>
                        <td><?php echo $active ?></td>
                        <td><?php echo $type ?></td>
                        <td>
                            
                        <?php 
                        $menu = get_admin_options_button('user', $row['user_id']); 
                        echo $menu;
                        ?>
                            
                        </td>
                    </tr>
	               <?php } ?>
                      </tbody>
                    </table>
      </div>
   </div>
</div>