<div class="sidebar-brand">
            <a href="<?php echo url() ?>"><?php echo $this->settings->title ?></a>
          </div>
          
              <ul class = "sidebar-menu">
				   <li><a class="nav-link" href="<?= url('admin/') ?>"><i class="fas fa-columns"></i> <span>Dashboard</span></a></li>
              <li class="menu-header">General</li>
				  
            <li><a class="nav-link" href="<?= url('admin/settings') ?>"><i class="fas fa-cog"></i> <span>General Settings</span></a></li>
            <li><a class="nav-link" href="<?= url('admin/features') ?>"><i class="fas fa-globe-americas"></i> <span>Website Features</span></a></li>
            <li><a class="nav-link" href="<?= url('admin/advanced') ?>"><i class="fas fa-terminal"></i> <span>Advanced Settings</span></a></li>
              
            
            <li class="menu-header">Users and CMS</li>
           <li><a class="nav-link" href="<?= url('admin/users') ?>"><i class="fas fa-user"></i> <span>Manage Users</span></a></li>
		   <li><a class="nav-link" href="<?= url('admin/pages') ?>"><i class="fas fa-scroll"></i> <span>Manage Pages</span></a></li>
		   <li><a class="nav-link" href="<?= url('admin/cms') ?>"><i class="fas fa-share"></i> <span>Create Post</span></a></li>
			  
            <li class="menu-header">Customization</li>
           <li><a class="nav-link" href="<?= url('admin/theme') ?>"><i class="fas fa-palette"></i> <span>Themes</span></a></li>
		   <li><a class="nav-link" href="<?= url('admin/plugins') ?>"><i class="fas fa-puzzle-piece"></i> <span>Plugins</span></a></li>
		    <li class="menu-header">Extras</li>
			<li><a class="nav-link" href="<?= url('admin/api') ?>"><i class="fas fa-cloud"></i> <span>Your website API</span></a></li>		  
				  
           <li><a class="nav-link" href="<?= url('admin/store') ?>"><i class="fas fa-store"></i> <span>Phoenix Store</span></a></li>
		   <li><a class="nav-link" href="<?= url('admin/changelog') ?>"><i class="fas fa-list-alt"></i> <span>Changelog</span></a></li>

          <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
            <a href="https://phoenix.ltda" target = "_blank" class="btn btn-primary btn-lg btn-block btn-icon-split">
              <i class="fas fa-fire"></i> Phoenix Website
            </a>
          </div>   

    