<div id="app">
    <?php display_notifications() ?>
    <div class="main-wrapper main-wrapper-1">
        <div class="navbar-bg"></div>
        <nav class="navbar navbar-expand-lg main-navbar"></nav>
        <!-- Main Content -->
        <div class="main-content">
            <section class="section">
                <div class="section-header">
                    <div class="section-header-back">
                        <a href="features-settings.html" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
                    </div>
                    <h1>Website Design</h1>
                </div>
                <div class="section-body">
                    <h2 class="section-title">All About theme Management</h2>
                    <p class="section-lead">
                        Here you can manage basic website design deatils, logo, and favicon.
                    </p>
                </div>
            </section>
            <div class="alert alert-primary alert-has-icon">
            <div class="alert-icon"><i class="far fa-lightbulb"></i></div>
                <div class="alert-body">
                    <div class="alert-title">Just a tip!</div>
                       Create a new theme to customize your website more efficiently and avoid over-writes during updates.
                    </div>
                </div>
           <div class="row">
            <div class="col-md-8">
              <div class="card">
                <div class="card-body">
                  <form action="" method="post" role="form" enctype="multipart/form-data">
                    <input type="hidden" name="token" value="<?= \Phoenix\Middlewares\Csrf::get() ?>" />
                    <div class = "form-group">
                        <input type = "text" class = "form-control" name = "primary_color" value = "<?php echo $this->settings->primary_color ?>">
                        <small class = "text-muted">Choose the primary color for your website.</small>
                    </div>
                    <div class = "form-group">
                        <input type = "text" class = "form-control" name = "secondary_color" value = "<?php echo $this->settings->secondary_color ?>">
                        <small class = "text-muted">Choose the secondary color for your website.</small>
                    </div>
					   <!-- <div class = "form-group">
                       <div class="custom-file">
        					<input type="file" class="custom-file-input" name = "logo" lang="en">
        					<label class="custom-file-label" for="customFileLang">Select file</label>
    					</div>
                        <small class="text-muted">This is the logo that will be displayed in the header and login page of your website.</small>
                        <small class="text-muted"><a href="admin/theme/removelogo<?= \Phoenix\Middlewares\Csrf::get_url_query() ?>">Remove Logo</a></small>
					</div>
                    </div>
                  
                      <div class = "form-group">
                       <div class="custom-file">
        					<input type="file" class="custom-file-input" name = "favicon" lang="en">
        					<label class="custom-file-label" for="customFileLang">Select file</label>
    					</div>
                        <small class="text-muted">This icon will be displayed in the browser tab.</small>
                                <small class="text-muted"><a href="admin/theme/removefavicon<?= \Phoenix\Middlewares\Csrf::get_url_query() ?>">Remove Favicon</a></small>
                        
					</div>
</div> -->
                     
                    
                    <div class="row">
	                   <?php
	                    foreach (get_themes() as $theme_path) {
	                    if (file_exists($theme_path . '/theme.xml')) {
	                    $t_details = read_xml_file($theme_path . '/theme.xml');
	                    $theme = str_replace(BASIC_THEME_PATH, '', $theme_path);

                      ?>

	                    <div class="col-6">
                        <div class="card" style = "margin: 10px">
                        <div class="card-body">
                            <h5 class="card-title"><b> <?php echo $t_details->theme_name ?></b></h5>
                            <b>Theme Author:</b> <?php echo $t_details->theme_author ?>    
                            <br>
                            <b>Description:</b> <?php echo $t_details->theme_desc ?>
                            <br>
                            <b>Version:</b> <?php echo $t_details->theme_version ?>
                            <br>
			                      <input type="radio" name="theme" value="<?php echo $t_details->theme_folder ?>"> Activate
                        </div>
                        </div>
                    </div>
	                <?php } } ?>
                    </div>
                    
                    <button type="submit" name = "submit" class="btn btn-primary">Save</button>
                    <div class="clearfix"></div>
                  </form>
                </div>
             </div>
				</div>
			  
          </div>
        </div>
    </div>
</div>